import Aside from "@/src/Components/aside/Aside";
import Head from "next/head";
import { motion } from "framer-motion";
export default function Home() {
  return (
    <>
      <Head>
        <title>Chiara De Santis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <motion.div
      animate={{ opacity: 1 }}
      initial={{ opacity: 0 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}>
        <Aside />
      </motion.div>
    </>
  );
}
